module.exports = {
  cover: {
    title1: "MANUAL BOOK",
    subtitle: "Petunjuk Pengoperasian & Perawatan",
    product1: "DUST COLLECTOR",
    product2: "PULSE JET BAG FILTER SYSTEM",
    capacity: "Kapasitas 10.000 CMH",
    photoCaption: "Foto Unit Dust Collector DCT10000",
    modelLabel: "Model: DCT10000",
    serialLabel: "No. Seri: 202608-001",
    yearLabel: "Tahun Pembuatan: 2026",
  },
  toc: { title: "Daftar Isi" },
  ch1: {
    title: "Pendahuluan",
    s11: "1.1 Tentang Dokumen Ini",
    p11a: "Manual book ini adalah panduan resmi untuk instalasi, pengoperasian, dan perawatan unit Dust Collector Pulse Jet kapasitas 10.000 CMH model DCT10000. Dokumen ini wajib dibaca dan dipahami oleh personel yang bertanggung jawab atas instalasi, operasional harian, dan perawatan unit sebelum menjalankan mesin.",
    p11b: "Simpan dokumen ini di tempat yang mudah diakses oleh operator dan teknisi perawatan. Jika unit dipindahtangankan, sertakan dokumen ini kepada pemilik/pengguna berikutnya.",
    s12: "1.2 Simbol & Peringatan Keselamatan",
    p12a: "Simbol berikut digunakan di sepanjang dokumen ini untuk menandai tingkat kepentingan informasi:",
    hazD: { label: "BAHAYA", text: "Potensi bahaya yang dapat menyebabkan cedera serius atau kematian jika tidak dihindari." },
    hazW: { label: "PERINGATAN", text: "Potensi bahaya yang dapat menyebabkan cedera ringan atau kerusakan peralatan." },
    hazN: { label: "CATATAN", text: "Informasi tambahan untuk pengoperasian atau perawatan unit secara optimal." },
  },
  ch2: {
    title: "Spesifikasi Teknis",
    specTable: [
      ["Parameter", "Nilai", "Satuan"],
      ["Model / Tipe Unit", "DCT10000", "-"],
      ["Kapasitas Udara (Air Volume)", "10.000", "m3/jam (CMH)"],
      ["Jenis Media Filter", "Filter Bag", "-"],
      ["Jumlah Cartridge / Bag", "64", "pcs"],
      ["Luas Total Media Filter", "≈ 39,6 (hasil perhitungan: π×0,128×1,54×64)", "m2"],
      ["Efisiensi Penyaringan", "≥ 99%", "%"],
      ["Daya Motor Blower", "7,5", "kW"],
      ["Tegangan Listrik", "380", "V/3ph/50Hz"],
      ["Proteksi Panel (IP Rating)", "IP52", "-"],
      ["Tekanan Udara Pulse Jet", "6", "kg/cm2 (bar)"],
      ["Kebutuhan Udara Kompresor", "≈ 0,1 (estimasi)", "Nm3/menit"],
      ["Jumlah Solenoid Valve", "8", "pcs"],
      ["Tegangan Coil Solenoid Valve", "24", "VDC"],
      ["Daya Coil Solenoid Valve", "15", "VA"],
      ["Proteksi Coil Solenoid Valve (IP Rating)", "IP65", "-"],
      ["Kapasitas Hopper", "500", "liter / kg"],
      ["Dimensi Unit (P x L x T)", "1650 x 1650 x 4300", "mm"],
      ["Berat Unit (kosong)", "1800", "kg"],
    ],
  },
  ch3: {
    title: "Komponen Utama & Fungsi",
    p3a: "Unit Dust Collector Pulse Jet DCT10000 terdiri dari komponen-komponen utama berikut:",
    icons: { housingFilter: "Housing/Filter", hopper: "Hopper", blowerFan: "Blower/Fan", pulseJet: "Pulse Jet", panelKontrol: "Panel Kontrol" },
    subA: "A. Housing / Rumah Filter",
    textA: "Ruang bertekanan negatif tempat proses penyaringan berlangsung. Di dalamnya terpasang filter bag yang menyaring debu dari aliran udara sebelum udara bersih dibuang ke atmosfer.",
    subB: "B. Hopper",
    textB: "Penampung sementara debu yang jatuh dari proses pembersihan filter, berbentuk kerucut agar debu mudah turun ke titik pembuangan.",
    subC: "C. Blower / Fan Sentrifugal",
    textC: "Menghasilkan tekanan negatif (isap) yang menarik udara kotor masuk ke housing dan mendorong udara bersih keluar melalui outlet/cerobong.",
    subD: "D. Sistem Pulse Jet (Air Tank & Solenoid Valve)",
    textD: "Menyimpan udara bertekanan dan menyemburkannya secara berkala ke dalam filter bag (arah berlawanan aliran normal) untuk merontokkan debu yang menempel di permukaan filter.",
    subE: "E. Panel Kontrol Listrik",
    textE: "Pusat kendali operasional unit: menghidupkan/mematikan blower, mengatur mode pembersihan pulse jet, dan menampilkan status operasi melalui lampu indikator.",
    subF: "F. Ducting & Damper (Butterfly Valve)",
    textF: "Saluran udara yang menghubungkan sumber debu ke unit, serta katup manual untuk mengatur/menutup aliran udara pada cabang ducting tertentu.",
  },
  ch4: {
    title: "Prinsip Kerja Pulse Jet Cleaning",
    p4a: "Dust collector jenis pulse jet bekerja dengan menyaring debu menggunakan media filter (bag) yang dibersihkan secara otomatis dan berkala menggunakan semburan udara bertekanan. Siklus kerjanya:",
    items: [
      "Udara kotor (mengandung debu) dihisap masuk ke housing melalui inlet duct oleh tekanan negatif dari blower.",
      "Partikel debu tertahan pada permukaan luar filter bag, sementara udara bersih menembus media filter.",
      "Udara bersih yang telah melewati filter dihisap blower dan dibuang keluar melalui outlet/cerobong.",
      "Debu yang menumpuk di permukaan filter meningkatkan tahanan aliran udara (pressure drop) di housing.",
      "Timer/pulse jet controller memicu solenoid valve secara bergantian per baris (header) sesuai interval yang diset.",
      "Udara bertekanan dari air tank menyembur balik (reverse pulse) ke dalam filter dalam sepersekian detik.",
      "Semburan ini melepaskan debu yang menempel pada filter, debu jatuh turun ke hopper penampung.",
      "Siklus berulang otomatis mengikuti pengaturan blow time dan blow interval di panel kontrol.",
    ],
    p4b: "Debu yang terkumpul di hopper dikeluarkan secara berkala melalui slide gate manual atau rotary airlock (opsional).",
  },
  ch5: {
    title: "Instalasi",
    s51: "5.1 Persiapan Lokasi & Pondasi",
    li51: [
      "Pastikan area pemasangan datar, daya dukung pondasi memadai untuk berat unit terisi debu.",
      "Sediakan ruang bebas di sekeliling unit untuk akses inspeksi, penggantian filter, dan perawatan.",
      "Pastikan lokasi terlindung dari hujan langsung kecuali unit didesain weatherproof.",
    ],
    s52: "5.2 Pemasangan Unit & Ducting",
    li52: [
      "Posisikan unit sesuai layout menggunakan alat angkat (crane/forklift) yang sesuai kapasitas.",
      "Sambungkan ducting inlet/outlet sesuai gambar instalasi.",
      "Gunakan hose clamp/flange yang sesuai pada sambungan fleksibel untuk mencegah kebocoran udara.",
      "Pastikan seluruh sambungan ducting kedap udara (airtight).",
    ],
    s53: "5.3 Sambungan Kelistrikan",
    hazW53: "Pekerjaan kelistrikan wajib oleh teknisi bersertifikat. Pastikan sumber listrik OFF sebelum penyambungan.",
    li53: [
      "Sambungkan suplai listrik utama ke terminal input panel sesuai spesifikasi nameplate.",
      "Pastikan grounding terpasang benar pada bodi panel dan motor.",
      "Periksa arah putaran motor blower sesuai tanda panah sebelum pengoperasian penuh.",
    ],
    s54: "5.4 Sambungan Udara Bertekanan",
    li54: [
      "Sambungkan suplai udara bertekanan dari kompresor ke inlet air tank pulse jet.",
      "Pastikan tekanan suplai sesuai spesifikasi (Bab 2).",
      "Disarankan memasang air dryer/filter regulator agar udara bebas kelembapan dan kotoran.",
    ],
    s55: "5.5 Pemeriksaan Sebelum Start-up Pertama",
    ck55: [
      "Tidak ada benda asing/alat kerja tertinggal di dalam housing atau ducting.",
      "Seluruh access door/panel inspeksi tertutup dan terkunci rapat.",
      "Seluruh baut/koneksi mekanikal dan kelistrikan sudah kencang.",
      "Sistem udara bertekanan sudah tersuplai dan tekanan sesuai spesifikasi.",
      "Safety guard pada bagian berputar (kopling/pulley blower) terpasang.",
    ],
  },
  ch6: {
    title: "Panduan Panel Kontrol",
    p6a: "Panel kontrol utama terletak di luar unit dan berfungsi sebagai pusat kendali operasional:",
    photoCaption61: "Gambar 6.1 - Panel Kontrol Tampak Luar",
    panelBtnTable: [
      ["Tombol / Indikator", "Fungsi"],
      ["Saklar Blower/Fan (风机启停)", "Menghidupkan/mematikan motor blower utama unit."],
      ["Indikator Debu - hijau (除尘指示)", "Menyala saat sistem dust collector beroperasi normal."],
      ["Selector Pulse Control (脉冲控制)", "Memilih mode pembersihan filter: OFF/Manual/Otomatis."],
      ["Indikator Pulse - hijau (脉冲指示)", "Menyala/berkedip saat solenoid valve menyembur."],
    ],
    p6b: "Di dalam panel kontrol terdapat komponen kelistrikan utama:",
    photoCaption62: "Gambar 6.2 - Komponen di Dalam Panel Kontrol",
    panelCompTable: [
      ["Komponen", "Fungsi"],
      ["QF1 - MCB/Breaker Utama", "Pemutus arus utama; proteksi hubung singkat/beban lebih & isolasi manual."],
      ["KM1 - Kontaktor Magnetik", "Menyambung/memutus suplai listrik ke motor blower."],
      ["Overload Relay (NXR-25)", "Proteksi motor dari beban lebih; tombol Stop/Reset manual."],
      ["Papan Timer Pulse Jet Controller", "Atur blow time, blow interval, & jumlah baris/valve output."],
    ],
    hazN6: "Lihat (Lampiran A).",
    subBmk: "Cara Setting Parameter BMK-10",
    p6c: "Spesifikasi board controller BMK-10 (No. BMK1605016), terdapat 3 parameter yang dapat disetting.",
    bmkTable: [
      ["Kode", "Parameter", "Rentang Nilai", "Setelan Saat Ini"],
      ["A", "Waktu semburan / pulse time (ON TIME)", "1 - 999 milidetik", "150 ms"],
      ["b", "Jeda antar semburan / pulse interval (OFF TIME)", "0 - 999 detik", "25 detik"],
      ["C", "Jumlah valve / circuit (jumlah baris solenoid aktif)", "1 - 17", "8"],
    ],
    p6d: "Panel menggunakan 4 tombol (K1-K4) untuk mengubah parameter di atas:",
    k1k4Table: [
      ["Tombol", "Fungsi"],
      ["K1 (设置 - Set)", "Memilih parameter yang akan diubah; tekan berulang hingga digit yang berkedip menunjukkan kode parameter yang dituju (A/b/C)."],
      ["K2 (加 - Tambah)", "Menambah nilai parameter yang sedang dipilih (▲ Naik)."],
      ["K3 (减 - Kurang)", "Mengurangi nilai parameter yang sedang dipilih (▼ Turun)."],
      ["K4 (确定 - Simpan)", "Menyimpan/konfirmasi nilai parameter yang telah diubah."],
    ],
    p6e: "Selector Pulse Control pada panel wajib berada di posisi Manual (手动) sebelum melakukan setting parameter. Contoh langkah mengubah parameter b (jeda antar semburan):",
    ol6: [
      "Pastikan Selector Pulse Control berada pada posisi Manual (手动).",
      "Tekan K1 (设置) berulang kali sampai digit yang berkedip menunjukkan parameter b.",
      "Tekan K2 (加) untuk menambah, atau K3 (减) untuk mengurangi nilai jeda (dalam detik).",
      "Tekan K4 (确定) untuk menyimpan.",
    ],
    p6f: "Langkah yang sama berlaku untuk parameter A dan C: tekan K1 hingga digit menunjukkan kode parameter yang dituju, ubah nilainya dengan K2/K3, lalu simpan dengan K4.",
    p6g: "Sebagai acuan awal: waktu semburan (A) sebaiknya tidak melebihi 100 milidetik - semburan lebih lama hanya memboroskan udara bertekanan tanpa menambah efek pembersihan. Jeda antar semburan (b) untuk siklus penuh tiap 2 menit dapat dihitung dari 120 detik dibagi nilai C (jumlah valve). Sesuaikan kembali berdasarkan kondisi debu aktual di lapangan.",
  },
  ch7: {
    title: "Panduan Pengoperasian",
    s71: "7.1 Prosedur Start-up",
    ol71: [
      "Pastikan seluruh pemeriksaan pra-start-up (Bab 5.5) telah dilakukan.",
      "Aktifkan sumber listrik utama pada panel distribusi (bukan panel unit).",
      "Tekan Saklar Blower ke posisi ON, pastikan indikator debu menyala.",
      "Atur Selector Pulse Control ke posisi Otomatis (Auto) untuk operasi normal.",
      "Buka suplai udara bertekanan ke sistem pulse jet, pastikan tekanan sesuai spesifikasi.",
      "Amati unit beberapa menit pertama, pastikan tidak ada suara/getaran/kebocoran abnormal.",
    ],
    p7a: "Urutan umum menghidupkan sistem secara berurutan (jika unit dilengkapi rotary airlock/proses hilir): 1) nyalakan rotary airlock (bila ada), 2) nyalakan timer/pulse jet controller, 3) nyalakan blower, 4) baru nyalakan peralatan proses/sumber debu.",
    s72: "7.2 Operasi Normal",
    li72: [
      "Pantau indikator pulse berkala untuk memastikan sistem pembersihan filter berjalan.",
      "Pantau differential pressure gauge - kenaikan berlebih menandakan filter perlu perawatan.",
      "Kosongkan hopper berkala sesuai jadwal untuk mencegah penumpukan debu berlebih.",
      "Catat parameter operasi (tekanan, arus motor) pada lembar log operasi harian.",
    ],
    s73: "7.3 Prosedur Shutdown",
    ol73: [
      "Hentikan peralatan proses/sumber debu terlebih dahulu.",
      "Biarkan sistem filter (blower + pulse jet) tetap beroperasi sekitar 10-15 menit setelah proses berhenti, agar sisa debu di ducting/housing tuntas tersaring.",
      "Tekan Saklar Blower ke posisi OFF.",
      "Biarkan timer/pulse jet dan rotary airlock (bila ada) tetap berjalan sekitar 10-15 menit lagi setelah blower mati, agar filter selesai dibersihkan dan sisa debu di hopper tertuntaskan.",
      "Tutup suplai udara bertekanan ke air tank, matikan timer/pulse jet dan airlock.",
      "Matikan sumber listrik utama jika unit tidak dioperasikan dalam waktu lama.",
    ],
    s74: "7.4 Kondisi Darurat / Emergency Stop",
    hazD74: "Dalam kondisi darurat (kebakaran, suara/getaran abnormal ekstrem, percikan api, bau terbakar), segera matikan unit melalui tombol Emergency Stop/panel distribusi utama dan hubungi teknisi/tim K3.",
  },
  ch8: {
    title: "Perawatan (Maintenance)",
    s81: "8.1 Jadwal Perawatan",
    maintTable: [
      ["Item Pemeriksaan", "Harian", "Mingguan", "Bulanan", "3-6 Bln"],
      ["Cek indikator panel & suara operasi", "✓", "", "", ""],
      ["Cek differential pressure gauge", "✓", "", "", ""],
      ["Kosongkan hopper", "✓", "", "", ""],
      ["Cek kebocoran udara ducting", "", "✓", "", ""],
      ["Drain kondensasi air tank pulse jet", "", "✓", "", ""],
      ["Cek fungsi solenoid valve", "", "✓", "", ""],
      ["Cek kekencangan baut & dudukan", "", "", "✓", ""],
      ["Cek kondisi belt/kopling blower", "", "", "✓", ""],
      ["Cek koneksi & kebersihan panel", "", "", "✓", ""],
      ["Inspeksi/ganti filter bag", "", "", "", "✓"],
      ["Pelumasan bearing blower", "", "", "", "✓"],
      ["Kalibrasi ulang timer pulse jet", "", "", "", "✓"],
    ],
    s82: "8.2 Perawatan Filter Bag",
    li82: [
      "Periksa kondisi fisik filter berkala - ganti jika robek, kotor permanen, atau efisiensi menurun drastis.",
      "Gunakan APD (masker debu, sarung tangan) saat membuka access door dan menangani filter.",
      "Catat siklus penggantian filter pada Lampiran B - Lembar Riwayat Perawatan.",
    ],
    pInstall: "Referensi umum tahapan pemasangan filter bag ke cage/venturi:",
    ol82: [
      "Masukkan cage (rangka) ke dalam filter bag.",
      "Lipat ujung atas bag ke bagian atas cage.",
      "Geser klem longgar melewati bag, tepat di atas alur penahan (detent).",
      "Geser bag & cage ke venturi hingga alur penahan terkunci.",
      "Kencangkan klem.",
    ],
    s83: "8.3 Perawatan Sistem Pulse Jet",
    li83: [
      "Buang kondensasi air pada air tank berkala melalui drain valve untuk mencegah karat.",
      "Periksa tekanan kerja pulse jet sesuai spesifikasi.",
      "Periksa setiap solenoid valve bekerja bergantian sesuai urutan (dengar suara semburan).",
    ],
    s84: "8.4 Perawatan Motor & Blower",
    li84: [
      "Lumasi bearing motor/blower sesuai jadwal & jenis pelumas rekomendasi pabrikan.",
      "Periksa kekencangan & kondisi belt/kopling berkala, ganti jika aus/retak.",
      "Pantau kebisingan & getaran; getaran berlebih menandakan ketidakseimbangan impeller/bearing rusak.",
    ],
    s85: "8.5 Perawatan Panel Listrik",
    li85: [
      "Matikan sumber listrik utama sebelum membuka panel (lockout-tagout).",
      "Periksa kekencangan terminal kabel, bersihkan debu/kotoran dari dalam panel.",
      "Periksa fungsi tombol, indikator, dan overload relay secara berkala.",
    ],
  },
  ch9: {
    title: "Troubleshooting",
    trbTable: [
      ["Gejala", "Kemungkinan Penyebab", "Tindakan Perbaikan"],
      ["Blower tidak menyala", "MCB (QF1) trip / kontaktor (KM1) rusak / fasa listrik tidak lengkap", "Periksa breaker & kontaktor, cek suplai 3 fasa. Hubungi teknisi listrik jika berlanjut."],
      ["Motor trip/overload berulang", "Beban motor berlebih, filter tersumbat, bearing macet", "Cek & bersihkan filter, periksa bearing, cek setting overload (NXR-25)."],
      ["Efisiensi turun / debu keluar dari outlet", "Filter robek/rusak, sambungan ke tube sheet bocor, filter jenuh", "Periksa & ganti filter, periksa gasket/seal dudukan filter."],
      ["Pulse valve tidak bekerja", "Timer controller tidak aktif, solenoid rusak, suplai udara tidak ada", "Cek mode pulse control (Auto), cek suplai udara, ganti solenoid rusak."],
      ["Tekanan pulse jet rendah", "Kompresor tidak memadai, kebocoran pipa, regulator salah setting", "Cek kapasitas kompresor, periksa kebocoran, sesuaikan regulator."],
      ["Suara bising/getaran berlebih", "Impeller tidak seimbang, bearing aus, baut dudukan kendor", "Matikan unit, periksa baut, bearing, dan impeller. Hubungi teknisi jika perlu."],
      ["Differential pressure terus naik", "Filter jenuh/tersumbat, pulse jet tidak efektif", "Cek fungsi pulse jet (Bab 8.3), jadwalkan penggantian filter lebih awal."],
    ],
  },
  ch10: {
    title: "Keselamatan Kerja (K3)",
    hazD10: "Selalu matikan & kunci sumber listrik (lockout-tagout) sebelum perawatan, perbaikan, atau pembersihan bagian dalam unit.",
    li10: [
      "Gunakan APD sesuai: masker debu/respirator, sarung tangan, pelindung mata, sepatu safety.",
      "Jangan membuka access door/panel inspeksi saat unit beroperasi.",
      "Untuk debu combustible, lakukan kajian risiko (dust hazard analysis) sesuai standar (mis. NFPA 654).",
      "Dilarang merokok/membawa sumber api terbuka di sekitar unit & area penyimpanan debu.",
      "Pastikan area sekitar unit bebas material mudah terbakar.",
      "Hanya personel terlatih & berwenang yang boleh instalasi, operasi, dan perawatan unit.",
      "Pastikan seluruh guard/pelindung bagian berputar terpasang sebelum unit dioperasikan.",
    ],
  },
  ch11: {
    title: "Lampiran",
    subA: "Lampiran A - Diagram Kelistrikan",
    pA: "Contoh topologi kelistrikan umum sistem pulse jet dust collector (disconnect - starter blower - control box timer - solenoid valve). Gunakan sebagai referensi pemahaman, BUKAN diagram aktual unit ini.",
    subB: "Lampiran B - Lembar Riwayat Perawatan",
    maintHistHeader: ["Tanggal", "Kegiatan Perawatan", "Teknisi", "Catatan"],
    subC: "Lampiran C - Gambar Explode",
    pC: "Contoh susunan bertingkat komponen unit pulse jet bag filter (referensi umum). Padankan istilah berikut dengan label pada gambar:",
    legendTable: [
      ["Label (EN)", "Keterangan"],
      ["PLENUM", "Ruang bersih di atas tubesheet, tempat pulse jet menyembur"],
      ["TUBESHEET", "Pelat dudukan filter bag"],
      ["BAG SECTION", "Bagian housing tempat filter bag terpasang"],
      ["HOPPER", "Penampung debu kerucut"],
      ["LEGS", "Kaki penyangga unit"],
    ],
  },
};
